name: hello_world
on: push

jobs:
  build:
    name: hello_world_action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "MonaLisa"
